apiVersion: apps/v1
kind: Deployment
metadata:
  name: bring-me-be
spec:
  selector:
    matchLabels:
      app: bring-me-be
  template:
    containers:
    - name: bring-me-be
      env:
        - name: NODE_ENV
          value: 'development'
        - name: POSTGRES_NAME
          value: development