version: '3.7'
services:
  app:
    build: .
    command: npm start
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres:alpine
    volumes:
      - bringme:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=bringme
    ports:
      - '5432:5432'

volumes:
  bringme:
    name: bringmeDB
