version: '3.7'
services:
  app:
    build: .
    command: npm run start:prod
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - '3000'
    ports:
      - '3000:3000'
      - '5000:5000'
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres:alpine
    volumes:
      - bringme:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=bringme
    ports:
      - '5432:5432'

volumes:
  bringme:
    name: bringmeDB
