apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - svc.yaml

commonAnnotations:
  app.gitlab.com/env: $CI_ENVIRONMENT_SLUG
  app.gitlab.com/app: $CI_PROJECT_PATH_SLUG
